---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on BSD
permissions:
  contents: read
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '13.3'
            pkginstall: |
              sudo pkg install -y p5-ExtUtils-MakeMaker p5-JSON-MaybeXS p5-IPC-System-Simple p5-Test-Needs
              sudo pkg install -y p5-Params-Util p5-LWP-Protocol-https p5-Test-NoWarnings
              sudo pkg install -y p5-Devel-StackTrace
          - name: openbsd
            version: '7.5'
            pkginstall: |
              pkg_add p5-JSON-MaybeXS p5-LWP-Protocol-https p5-Params-Util

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo hostname example.com
            sudo ${{ matrix.os.pkginstall }}
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure --with-develop .
            sudo chown -R runner:runner .
            AUTOMATED_TESTING=1 perl Makefile.PL
            AUTOMATED_TESTING=1 make
            AUTOMATED_TESTING=1 prove -wlmb t
